site_name:  Veendorp Roleplay
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
  language: nl
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: img/logo.png
  logo: img/logo.png






